
name: 'oms_analytics'
version: '1.0.0'
config-version: 2


profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:  
  - "target"
  - "dbt_packages"

# You can apply hooks at the folder level (applies to all models in the folder)
# or at the individual model level. Hooks can be defined as inline SQL or as macros.

models:
  oms_analytics:
    +schema: l1_landing
    +materialized: table
    +transient: false

    customer_rev:
      +pre-hook:
        - "{{ log_start_time(this) }}"
      +post-hook:
        - "{{ log_end_time(this) }}"

    hooks_demo:
      cust_orders_11:
        +pre-hook:
          - |
            INSERT INTO audit.model_runs (model_name, run_type, run_timestamp)
            VALUES ('{{ this }}', 'start', CURRENT_TIMESTAMP)
        +post-hook:
          - |
            INSERT INTO audit.model_runs (model_name, run_type, run_timestamp)
            VALUES ('{{ this }}', 'end', CURRENT_TIMESTAMP)
